name: Hello Test #Имя проекта
on: push #Отрабатывать при пуше

jobs:
 build:   #Имя задачи (ID)
  runs-on: ubuntu-latest #На какой ОС запускать


  steps:
   - run: tar -czvf practice.tar.gz /home/anastasia/practice/ #Какая команда выполнится при пуше
  
